### ISSUE TITLE
Suspicious cursor stack in ConditionalOnBeanAnyNestedCondition has a ClassDeclaration as its own parent

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-spring#111]
ConditionalOnBeanAnyNestedConditionTest > simpleConditionalAnnotationMultipleTypeClassNames

When evaluating the cursor stack for `ConfigClass`, it was noticed that the cursor stack seems to think the `ClassDeclaration` value for `ConfigClass` has a parent of `ClassDeclaration` with a value of... `ConfigClass`. As in, it appeared to think it was the parent of itself.

In addition to it being weird that a ClassDecl is located on the cursor path twice, this shouldn't be possible, because these should at least be separated by a `Block` AST element. 

Linking:
- https://github.com/openrewrite/rewrite-spring/commit/7e50888f067145c86cf30557892e48dfcc48640b
- https://github.com/openrewrite/rewrite-spring/commit/d2837b698ceedd3d3f07751b0f5240b6090e4339

Screenshot showing what is being referred to:

![Screen Shot 2021-11-03 at 8 25 43 PM](https://user-images.githubusercontent.com/5619476/140242008-2546da4a-2371-432b-a707-ce98328c5366.png)

**Comment by traceyyoshima** [comment]
Thanks for opening the issue, I looked into the cursor example and it turned out to be normal.

The provided example will happen when maybeAutoformat is called on a J.ClassDeclaration.
Each of the formatting visitors fork the cursor in AutoformatVisitor:
`J t = new NormalizeFormatVisitor<>(stopAfter).visit(tree, p, cursor.fork());`

The fork allows us to use messages without interacting with the original call.

Eventually, the parent is set (in this case ClassDec) `setCursor(new Cursor(cursor, tree));` and we visit tree (ClassDec).
