### ISSUE TITLE
Add verbose option to UpgradeSpringBoot_3_0

### ISSUE THREAD

**Issue by fertroya** [openrewrite/rewrite-spring#378]
## What problem are you trying to solve?

I was reporting a bug where the build got stuck in "Running recipe(s)..." for more than 5 minutes when it finally finished successfully.

## Describe the solution you'd like

It'd avoid confusion if progress would be reported.

## Have you considered any alternatives or workarounds?

Yes, I've tried with '-X' and '-e' Maven options with no success.

## Are you interested in contributing this feature to OpenRewrite?

Never thought of it, this seems like a good one to start.

**Comment by timtebeek** [comment]
Hi @fertroya ! Thanks for reporting your experience here. From your description it sounds like you're using the Maven plugin, and we have a similar issue open over on https://github.com/openrewrite/rewrite-maven-plugin/issues/544 to track progress reporting there.

Hope you don't mind me closing this issue as a duplicate, since it's covered more extensively in rewrite-maven-plugin and not related to rewrite-spring specifically. Welcome to chime in & help out over on that issue!

**Comment by fertroya** [comment]
Hey @timtebeek thanks for the promptly response! I'll _check progress_ on that one then :-)
