### ISSUE TITLE
spring-data-commons changed AuditorAware from 1.x to 2.x

### ISSUE THREAD

**Issue by Jenson3210** [openrewrite/rewrite-spring#613]
## What problem are you trying to solve?
Migrating between Spring boot 1 and 2, the implementation of AuditorAware changed. 

## Describe the situation before applying the recipe
see [the code](https://github.com/spring-projects/spring-data-commons/blob/1.13.23.RELEASE/src/main/java/org/springframework/data/domain/AuditorAware.java#L31)
```java
public class AuditorAwareImpl implements AuditorAware<String> {
    public String getCurrentAuditor() {
        return "Some code here";
    }
}
```

## Describe the situation after applying the recipe
see [the code](https://github.com/spring-projects/spring-data-commons/blob/2.0.0.RELEASE/src/main/java/org/springframework/data/domain/AuditorAware.java#L33)
```java
public class AuditorAwareImpl implements AuditorAware<String> {
    public Optional<String> getCurrentAuditor() {
        return Optional.ofNullable("Some code here");
    }
}
```

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
This should be an easy one. Will see, if no one picks it up sooner.

**Comment by timtebeek** [comment]
Indeed looks fairly straightforward; thanks for calling this out! Best to start with tests, and then introduce a visitor that
1. overrides `visitMethodDeclaration`
2. uses a MethodMatcher to see if it's `getCurrentAuditor`
3. if the return type is already an Optional, return early
4. otherwise change the method return type
5. and wrap any returned expression in an `Optional.ofNullable` method invocation

**Comment by Jenson3210** [comment]
any hint on the changing of the return type?
